[tools]
rojo = "rojo-rbx/rojo@7.4.0"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.24.0"
stylua = "johnnymorganz/stylua@0.16.1"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"