[package]
name = "luarook/suitup-technical-challenge"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileService = "alreadypro/profileservice@1.0.4"

[dependencies]
Knit = "sleitnick/knit@1.6.0"
Comm = "sleitnick/comm@1.0.1"
Component = "sleitnick/component@2.4.8"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.1.0"
Signal = "sleitnick/signal@2.0.1"
Loader = "sleitnick/loader@2.0.0"
ReplicaService = "brittonfischer/replicaservice@0.1.0"
TableUtil = "sleitnick/table-util@1.2.1"	