[package]
name = "luarook/suitup-technical-challenge"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileService = "alreadypro/profileservice@1.0.4"

[dependencies]
Comm = "sleitnick/comm@1.0.1" # Comm is used to bridge the server and client. While it comes pre-installed with Knit, I'm installing it for my BridgeExtension.
Component = "sleitnick/component@2.4.8" # Component allows for me to easily bind code to CollectionService tags and provide modular API.
FastcastRedux = "encodedvenom/fastcastredux@0.1.3" # Fastcast is used for simulating bullet physics.
Knit = "sleitnick/knit@1.6.0" # Knit is used as the games framework.
Loader = "sleitnick/loader@2.0.0" # Loader is utilized to simplify the Knit boostrapper.
Observers = "sleitnick/observers@^0.3.3" # Observers are used to simplify binding behavior to players / characters.
Promise = "evaera/promise@4.0.0"
React = "jsdotlua/react@17.0.2" # Used for creating reactive and component-based UI (such as the health bar, menu, and score UI)
ReactRoblox = "jsdotlua/react-roblox@17.0.2" # Used for creating reactive and component-based UI (such as the health bar, menu, and score UI)
ReplicaService = "brittonfischer/replicaservice@0.1.0" # ReplicaService is used to replicate profile data to the client.
Signal = "sleitnick/signal@2.0.1" # Signal is used to provide events (such as Launcher.TargetHit) for the developer to connect to.
TableUtil = "sleitnick/table-util@1.2.1" # Used to merge/reconcile source props with template props.
Timer = "sleitnick/timer@1.1.2" # Used to run behavior on intervals, such as the Spawn Pads.
Trove = "sleitnick/trove@1.1.0" # Used for cleanup.